-- MySQL Script generated by MySQL Workbench
-- Thu Apr 24 18:23:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project_travelo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project_travelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_travelo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `project_travelo` ;

-- -----------------------------------------------------
-- Table `project_travelo`.`administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`administrator` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`administrator` (
  `administrator_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `hasło_hash` VARCHAR(255) NOT NULL,
  `imię` VARCHAR(100) NOT NULL,
  `rola` ENUM('moderator', 'finanse', 'wsparcie') NOT NULL DEFAULT 'moderator',
  `jest_aktywny` TINYINT(1) NOT NULL DEFAULT '1',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`administrator_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `email` ON `project_travelo`.`administrator` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`atrakcja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`atrakcja` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`atrakcja` (
  `atrakcja_id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(255) NOT NULL,
  `opis` TEXT NOT NULL,
  `miasto_id` INT NOT NULL,
  `kategoria` VARCHAR(50) NOT NULL,
  `przyjazne_dla_mobilności` TINYINT(1) NOT NULL DEFAULT '0',
  `cena` DECIMAL(10,2) NOT NULL,
  `liczba_miejsc` INT NOT NULL,
  `wideo_url` TEXT NULL DEFAULT NULL,
  `średnia_ocena` DECIMAL(3,2) NULL DEFAULT NULL,
  `polityka_anulowania` TEXT NULL DEFAULT NULL,
  `partner_id` INT NOT NULL,
  PRIMARY KEY (`atrakcja_id`),
  CONSTRAINT `fk_atrakcja_miasto_id`
    FOREIGN KEY (`miasto_id`)
    REFERENCES `project_travelo`.`miasto` (`miasto_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_atrakcja_partner_id`
    FOREIGN KEY (`partner_id`)
    REFERENCES `project_travelo`.`partner` (`partner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `partner_id` ON `project_travelo`.`atrakcja` (`partner_id` ASC) VISIBLE;

CREATE INDEX `idx_miasto_id` ON `project_travelo`.`atrakcja` (`miasto_id` ASC) VISIBLE;

CREATE INDEX `idx_cena` ON `project_travelo`.`atrakcja` (`cena` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`atrakcja_wycieczki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`atrakcja_wycieczki` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`atrakcja_wycieczki` (
  `wycieczka_id` INT NOT NULL,
  `atrakcja_id` INT NOT NULL,
  PRIMARY KEY (`wycieczka_id`, `atrakcja_id`),
  CONSTRAINT `atrakcje_wycieczek_ibfk_1`
    FOREIGN KEY (`wycieczka_id`)
    REFERENCES `project_travelo`.`wycieczka` (`wycieczka_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `atrakcje_wycieczek_ibfk_2`
    FOREIGN KEY (`atrakcja_id`)
    REFERENCES `project_travelo`.`atrakcja` (`atrakcja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `atrakcja_id` ON `project_travelo`.`atrakcja_wycieczki` (`atrakcja_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`bilet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`bilet` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`bilet` (
  `bilet_id` INT NOT NULL AUTO_INCREMENT,
  `rezerwacja_id` INT NOT NULL,
  `kod_qr` TEXT NOT NULL,
  `plik_pdf_url` TEXT NULL DEFAULT NULL,
  `ważny_do` DATE NOT NULL,
  PRIMARY KEY (`bilet_id`),
  CONSTRAINT `bilety_ibfk_1`
    FOREIGN KEY (`rezerwacja_id`)
    REFERENCES `project_travelo`.`rezerwacja` (`rezerwacja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `rezerwacja_id` ON `project_travelo`.`bilet` (`rezerwacja_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`dostępna_data_atrakcji`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`dostępna_data_atrakcji` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`dostępna_data_atrakcji` (
  `data_id` INT NOT NULL AUTO_INCREMENT,
  `atrakcja_id` INT NOT NULL,
  `data_dostępności` DATE NOT NULL,
  `liczba_miejsc` INT NOT NULL,
  PRIMARY KEY (`data_id`),
  CONSTRAINT `dostępne_daty_atrakcji_ibfk_1`
    FOREIGN KEY (`atrakcja_id`)
    REFERENCES `project_travelo`.`atrakcja` (`atrakcja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `atrakcja_id` ON `project_travelo`.`dostępna_data_atrakcji` (`atrakcja_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`historia_punktów`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`historia_punktów` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`historia_punktów` (
  `historia_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `punkty_dodane` INT NOT NULL DEFAULT '0',
  `punkty_wykorzystane` INT NOT NULL DEFAULT '0',
  `opis` TEXT NOT NULL,
  `data_zdarzenia` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`historia_id`),
  CONSTRAINT `fk_historia_punktow_klient_id`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `klient_id` ON `project_travelo`.`historia_punktów` (`klient_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`klient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`klient` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`klient` (
  `klient_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `telefon` VARCHAR(20) NULL DEFAULT NULL,
  `hasło_hash` VARCHAR(255) NOT NULL,
  `imię` VARCHAR(50) NOT NULL,
  `nazwisko` VARCHAR(50) NOT NULL,
  `data_urodzenia` DATE NULL DEFAULT NULL,
  `zdjęcie_profilowe` TEXT NULL DEFAULT NULL,
  `język` ENUM('en', 'pl') NOT NULL DEFAULT 'pl',
  `waluta` ENUM('PLN', 'EUR') NOT NULL DEFAULT 'PLN',
  `motyw` ENUM('jasny', 'ciemny') NOT NULL DEFAULT 'jasny',
  `jest_zablokowany` TINYINT(1) NOT NULL DEFAULT '0',
  `jest_vip` TINYINT(1) NOT NULL DEFAULT '0',
  `dwuskładnikowe_uwierzytelnianie_włączone` TINYINT(1) NOT NULL DEFAULT '0',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`klient_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `email` ON `project_travelo`.`klient` (`email` ASC) VISIBLE;

CREATE INDEX `idx_email` ON `project_travelo`.`klient` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`kraj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`kraj` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`kraj` (
  `kraj_id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`kraj_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `nazwa` ON `project_travelo`.`kraj` (`nazwa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`log_administratora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`log_administratora` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`log_administratora` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `administrator_id` INT NOT NULL,
  `typ_akcji` VARCHAR(100) NOT NULL,
  `opis_akcji` TEXT NOT NULL,
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  CONSTRAINT `logi_administratorów_ibfk_1`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `project_travelo`.`administrator` (`administrator_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `administrator_id` ON `project_travelo`.`log_administratora` (`administrator_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`miasto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`miasto` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`miasto` (
  `miasto_id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(100) NOT NULL,
  `kraj_id` INT NOT NULL,
  `gps_szerokość` DECIMAL(9,6) NOT NULL,
  `gps_długość` DECIMAL(9,6) NOT NULL,
  PRIMARY KEY (`miasto_id`),
  CONSTRAINT `miasta_ibfk_1`
    FOREIGN KEY (`kraj_id`)
    REFERENCES `project_travelo`.`kraj` (`kraj_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `kraj_id` ON `project_travelo`.`miasto` (`kraj_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`obraz_recenzji`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`obraz_recenzji` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`obraz_recenzji` (
  `obraz_id` INT NOT NULL AUTO_INCREMENT,
  `recenzja_id` INT NOT NULL,
  `url_obrazu` TEXT NOT NULL,
  PRIMARY KEY (`obraz_id`),
  CONSTRAINT `obrazy_recenzji_ibfk_1`
    FOREIGN KEY (`recenzja_id`)
    REFERENCES `project_travelo`.`recenzja` (`recenzja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `recenzja_id` ON `project_travelo`.`obraz_recenzji` (`recenzja_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`oczekujący_klient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`oczekujący_klient` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`oczekujący_klient` (
  `oczekujący_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `typ_uslugi` ENUM('atrakcja', 'zakwaterowanie') NOT NULL,
  `pożądana_data` DATE NOT NULL,
  `uczestnicy` INT NOT NULL,
  `atrakcja_id` INT NULL DEFAULT NULL,
  `zakwaterowanie_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`oczekujący_id`),
  CONSTRAINT `fk_oczekujący_klient_atrakcja_id`
    FOREIGN KEY (`atrakcja_id`)
    REFERENCES `project_travelo`.`atrakcja` (`atrakcja_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_oczekujący_klient_klient_id`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_oczekujący_klient_zakwaterowanie_id`
    FOREIGN KEY (`zakwaterowanie_id`)
    REFERENCES `project_travelo`.`zakwaterowanie` (`zakwaterowanie_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `uk_oczekujący_klient` ON `project_travelo`.`oczekujący_klient` (`klient_id` ASC, `atrakcja_id` ASC, `zakwaterowanie_id` ASC) VISIBLE;

CREATE INDEX `klient_id` ON `project_travelo`.`oczekujący_klient` (`klient_id` ASC) VISIBLE;

CREATE INDEX `idx_typ_uslugi` ON `project_travelo`.`oczekujący_klient` (`typ_uslugi` ASC) VISIBLE;

CREATE INDEX `idx_atrakcja_id` ON `project_travelo`.`oczekujący_klient` (`atrakcja_id` ASC) VISIBLE;

CREATE INDEX `idx_zakwaterowanie_id` ON `project_travelo`.`oczekujący_klient` (`zakwaterowanie_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`odpowiedź_na_recenzję`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`odpowiedź_na_recenzję` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`odpowiedź_na_recenzję` (
  `odpowiedź_id` INT NOT NULL AUTO_INCREMENT,
  `recenzja_id` INT NOT NULL,
  `partner_id` INT NOT NULL,
  `tekst_odpowiedzi` TEXT NOT NULL,
  `utworzono_w` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`odpowiedź_id`),
  CONSTRAINT `odpowiedzi_na_recenzje_ibfk_1`
    FOREIGN KEY (`recenzja_id`)
    REFERENCES `project_travelo`.`recenzja` (`recenzja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `odpowiedzi_na_recenzje_ibfk_2`
    FOREIGN KEY (`partner_id`)
    REFERENCES `project_travelo`.`partner` (`partner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `recenzja_id` ON `project_travelo`.`odpowiedź_na_recenzję` (`recenzja_id` ASC) VISIBLE;

CREATE INDEX `partner_id` ON `project_travelo`.`odpowiedź_na_recenzję` (`partner_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`partner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`partner` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`partner` (
  `partner_id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(100) NOT NULL,
  `opis` TEXT NULL DEFAULT NULL,
  `adres` TEXT NULL DEFAULT NULL,
  `email_kontaktowy` VARCHAR(100) NOT NULL,
  `telefon_kontaktowy` VARCHAR(20) NULL DEFAULT NULL,
  `strona_internetowa` VARCHAR(100) NULL DEFAULT NULL,
  `zweryfikowany` TINYINT(1) NOT NULL DEFAULT '0',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`partner_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `email_kontaktowy_UNIQUE` ON `project_travelo`.`partner` (`email_kontaktowy` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`polityka_bezpieczeństwa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`polityka_bezpieczeństwa` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`polityka_bezpieczeństwa` (
  `polityka_id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(100) NOT NULL,
  `wartość` TEXT NULL DEFAULT NULL,
  `opis` TEXT NULL DEFAULT NULL,
  `zaktualizowano_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`polityka_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `project_travelo`.`post_zawartości`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`post_zawartości` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`post_zawartości` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `tytuł` VARCHAR(255) NOT NULL,
  `treść` TEXT NOT NULL,
  `tagi` TEXT NOT NULL,
  `słowa_kluczowe_seo` TEXT NOT NULL,
  `utworzony_przez` INT NULL DEFAULT NULL,
  `opublikowano_w` TIMESTAMP NOT NULL,
  `jest_opublikowany` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`post_id`),
  CONSTRAINT `fk_post_zawartości_administrator_id`
    FOREIGN KEY (`utworzony_przez`)
    REFERENCES `project_travelo`.`administrator` (`administrator_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_utworzony_przez` ON `project_travelo`.`post_zawartości` (`utworzony_przez` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`powiadomienie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`powiadomienie` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`powiadomienie` (
  `powiadomienie_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `typ` VARCHAR(50) NOT NULL,
  `treść` TEXT NOT NULL,
  `czy_przeczytane` TINYINT(1) NOT NULL DEFAULT '0',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `powiadomieniecol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`powiadomienie_id`),
  CONSTRAINT `powiadomienia_ibfk_1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `użytkownik_id` ON `project_travelo`.`powiadomienie` (`klient_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`preferencja_wypłaty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`preferencja_wypłaty` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`preferencja_wypłaty` (
  `partner_id` INT NOT NULL,
  `minimalna_wypłata` DECIMAL(10,2) NOT NULL DEFAULT '100.00',
  `częstotliwość_wypłat` ENUM('tygodniowa', 'miesięczna', 'na_żądanie') NOT NULL DEFAULT 'miesięczna',
  `stripe_konto_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`partner_id`),
  CONSTRAINT `fk_preferencja_wypłaty_partner_id`
    FOREIGN KEY (`partner_id`)
    REFERENCES `project_travelo`.`partner` (`partner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `project_travelo`.`program_lojalnościowy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`program_lojalnościowy` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`program_lojalnościowy` (
  `użytkownik_id` INT NOT NULL,
  `punkty` INT NOT NULL DEFAULT '0',
  `poziom` ENUM('brązowy', 'srebrny', 'złoty') NOT NULL DEFAULT 'brązowy',
  `kod_polecający` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`użytkownik_id`),
  CONSTRAINT `program_lojalnościowy_ibfk_1`
    FOREIGN KEY (`użytkownik_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `kod_polecający` ON `project_travelo`.`program_lojalnościowy` (`kod_polecający` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`promocja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`promocja` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`promocja` (
  `promocja_id` INT NOT NULL AUTO_INCREMENT,
  `kod` VARCHAR(50) NOT NULL,
  `opis` TEXT NULL DEFAULT NULL,
  `procent_rabatu` INT NOT NULL,
  `ważne_od` DATE NOT NULL,
  `ważne_do` DATE NOT NULL,
  `minimalna_kwota_rezerwacji` DECIMAL(10,2) NOT NULL,
  `limit_użyć` INT NOT NULL,
  PRIMARY KEY (`promocja_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `kod` ON `project_travelo`.`promocja` (`kod` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`promocja_użytkownik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`promocja_użytkownik` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`promocja_użytkownik` (
  `promocja_id` INT NOT NULL,
  `klient_id` INT NOT NULL,
  `liczba_użyć` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`promocja_id`, `klient_id`),
  CONSTRAINT `fk_promocje_has_użytkownicy_promocje1`
    FOREIGN KEY (`promocja_id`)
    REFERENCES `project_travelo`.`promocja` (`promocja_id`),
  CONSTRAINT `fk_promocje_has_użytkownicy_użytkownicy1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_promocje_has_użytkownicy_użytkownicy1_idx` ON `project_travelo`.`promocja_użytkownik` (`klient_id` ASC) VISIBLE;

CREATE INDEX `fk_promocje_has_użytkownicy_promocje1_idx` ON `project_travelo`.`promocja_użytkownik` (`promocja_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`płatnośc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`płatnośc` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`płatnośc` (
  `płatność_id` INT NOT NULL AUTO_INCREMENT,
  `rezerwacja_id` INT NOT NULL,
  `dostawca_płatności` VARCHAR(50) NOT NULL,
  `status_płatności` ENUM('udane', 'nieudane', 'zwrócone') NOT NULL DEFAULT 'udane',
  `data_transakcji` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`płatność_id`),
  CONSTRAINT `płatności_ibfk_1`
    FOREIGN KEY (`rezerwacja_id`)
    REFERENCES `project_travelo`.`rezerwacja` (`rezerwacja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `rezerwacja_id` ON `project_travelo`.`płatnośc` (`rezerwacja_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`raport_finansowy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`raport_finansowy` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`raport_finansowy` (
  `raport_id` INT NOT NULL AUTO_INCREMENT,
  `partner_id` INT NULL DEFAULT NULL,
  `data_raportu` DATE NOT NULL,
  `całkowity_przychód` DECIMAL(12,2) NOT NULL,
  `całkowita_wypłata` DECIMAL(12,2) NOT NULL,
  `oczekujące_saldo` DECIMAL(12,2) NOT NULL,
  `pobrano` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`raport_id`),
  CONSTRAINT `raporty_finansowe_ibfk_1`
    FOREIGN KEY (`partner_id`)
    REFERENCES `project_travelo`.`partner` (`partner_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `partner_id` ON `project_travelo`.`raport_finansowy` (`partner_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`recenzja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`recenzja` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`recenzja` (
  `recenzja_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NULL DEFAULT NULL,
  `typ_elementu` ENUM('atrakcja', 'zakwaterowanie') NOT NULL,
  `obiekt_id` INT NOT NULL,
  `ocena` INT NOT NULL,
  `komentarz` TEXT NULL DEFAULT NULL,
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`recenzja_id`),
  CONSTRAINT `fk_recenzja_klient_id`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_klient_id` ON `project_travelo`.`recenzja` (`klient_id` ASC) VISIBLE;

CREATE INDEX `idx_ocena` ON `project_travelo`.`recenzja` (`ocena` ASC) VISIBLE;

CREATE INDEX `idx_typ_elementu_obiekt_id` ON `project_travelo`.`recenzja` (`typ_elementu` ASC, `obiekt_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`reguła_ceny`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`reguła_ceny` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`reguła_ceny` (
  `reguła_id` INT NOT NULL AUTO_INCREMENT,
  `partner_id` INT NOT NULL,
  `typ_uslugi` ENUM('atrakcja', 'zakwaterowanie') NOT NULL,
  `typ_reguły` ENUM('sezonowa', 'rabat', 'dynamiczna') NOT NULL,
  `opis` TEXT NULL DEFAULT NULL,
  `modyfikator_ceny` DECIMAL(5,2) NOT NULL,
  `ważne_od` DATE NOT NULL,
  `ważne_do` DATE NOT NULL,
  `atrakcja_atrakcja_id` INT NULL DEFAULT NULL,
  `zakwaterowanie_zakwaterowanie_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`reguła_id`),
  CONSTRAINT `fk_reguła_ceny_atrakcja1`
    FOREIGN KEY (`atrakcja_atrakcja_id`)
    REFERENCES `project_travelo`.`atrakcja` (`atrakcja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reguła_ceny_zakwaterowanie1`
    FOREIGN KEY (`zakwaterowanie_zakwaterowanie_id`)
    REFERENCES `project_travelo`.`zakwaterowanie` (`zakwaterowanie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `reguły_cen_ibfk_1`
    FOREIGN KEY (`partner_id`)
    REFERENCES `project_travelo`.`partner` (`partner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `partner_id` ON `project_travelo`.`reguła_ceny` (`partner_id` ASC) VISIBLE;

CREATE INDEX `idx_typ_elementu_obiekt_id` ON `project_travelo`.`reguła_ceny` (`typ_uslugi` ASC) VISIBLE;

CREATE INDEX `fk_reguła_ceny_atrakcja1_idx` ON `project_travelo`.`reguła_ceny` (`atrakcja_atrakcja_id` ASC) VISIBLE;

CREATE INDEX `fk_reguła_ceny_zakwaterowanie1_idx` ON `project_travelo`.`reguła_ceny` (`zakwaterowanie_zakwaterowanie_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`rekomendacja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`rekomendacja` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`rekomendacja` (
  `rekomendacja_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `typ_uslugi` ENUM('atrakcja', 'zakwaterowanie') NOT NULL,
  `waga_rekomendacji` DECIMAL(5,2) NOT NULL,
  `typ_rekomendacji` ENUM('algorytmiczna', 'użytkownika', 'promocyjna') NOT NULL,
  `opis` TEXT NOT NULL,
  `atrakcja_id` INT NULL DEFAULT NULL,
  `zakwaterowanie_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`rekomendacja_id`),
  CONSTRAINT `fk_rekomendacja_atrakcja1`
    FOREIGN KEY (`atrakcja_id`)
    REFERENCES `project_travelo`.`atrakcja` (`atrakcja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rekomendacja_zakwaterowanie1`
    FOREIGN KEY (`zakwaterowanie_id`)
    REFERENCES `project_travelo`.`zakwaterowanie` (`zakwaterowanie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `rekomendacje_ibfk_1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_użytkownik_id` ON `project_travelo`.`rekomendacja` (`klient_id` ASC) VISIBLE;

CREATE INDEX `idx_typ_elementu_obiekt_id` ON `project_travelo`.`rekomendacja` (`typ_uslugi` ASC) VISIBLE;

CREATE INDEX `fk_rekomendacja_atrakcja1_idx` ON `project_travelo`.`rekomendacja` (`atrakcja_id` ASC) VISIBLE;

CREATE INDEX `fk_rekomendacja_zakwaterowanie1_idx` ON `project_travelo`.`rekomendacja` (`zakwaterowanie_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`rezerwacja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`rezerwacja` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`rezerwacja` (
  `rezerwacja_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `typ_elementu` ENUM('atrakcja', 'zakwaterowanie') NOT NULL,
  `obiekt_id` INT NOT NULL,
  `data_id` INT NOT NULL,
  `data_rezerwacji` DATE NOT NULL,
  `zameldowanie` DATE NOT NULL,
  `wymeldowanie` DATE NOT NULL,
  `uczestnicy` INT NOT NULL,
  `całkowita_cena` DECIMAL(10,2) NOT NULL,
  `status` ENUM('potwierdzone', 'oczekujące', 'anulowane') NOT NULL DEFAULT 'oczekujące',
  `faktura_status` ENUM('nie_żądana', 'oczekująca', 'wysłana') NOT NULL DEFAULT 'nie_żądana',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`rezerwacja_id`),
  CONSTRAINT `rezerwacje_ibfk_1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `rezerwacje_ibfk_2`
    FOREIGN KEY (`data_id`)
    REFERENCES `project_travelo`.`dostępna_data_atrakcji` (`data_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `data_id` ON `project_travelo`.`rezerwacja` (`data_id` ASC) VISIBLE;

CREATE INDEX `idx_użytkownik_id` ON `project_travelo`.`rezerwacja` (`klient_id` ASC) VISIBLE;

CREATE INDEX `idx_data_rezerwacji` ON `project_travelo`.`rezerwacja` (`data_rezerwacji` ASC) VISIBLE;

CREATE INDEX `idx_status` ON `project_travelo`.`rezerwacja` (`status` ASC) VISIBLE;

CREATE INDEX `idx_typ_elementu_obiekt_id` ON `project_travelo`.`rezerwacja` (`typ_elementu` ASC, `obiekt_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`skarga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`skarga` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`skarga` (
  `skarga_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `rezerwacja_id` INT NULL DEFAULT NULL,
  `opis` TEXT NOT NULL,
  `status` ENUM('otwarta', 'w_przeglądzie', 'rozwiązana', 'odrzucona') NULL DEFAULT 'otwarta',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`skarga_id`),
  CONSTRAINT `skargi_ibfk_1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `skargi_ibfk_2`
    FOREIGN KEY (`rezerwacja_id`)
    REFERENCES `project_travelo`.`rezerwacja` (`rezerwacja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `użytkownik_id` ON `project_travelo`.`skarga` (`klient_id` ASC) VISIBLE;

CREATE INDEX `rezerwacja_id` ON `project_travelo`.`skarga` (`rezerwacja_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`skarga_na_partnera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`skarga_na_partnera` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`skarga_na_partnera` (
  `skarga_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `partner_id` INT NOT NULL,
  `opis` TEXT NOT NULL,
  `status` ENUM('nowa', 'w_przeglądzie', 'rozwiązana', 'zamknięta') NULL DEFAULT 'nowa',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`skarga_id`),
  CONSTRAINT `skargi_na_partnerów_ibfk_1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `skargi_na_partnerów_ibfk_2`
    FOREIGN KEY (`partner_id`)
    REFERENCES `project_travelo`.`partner` (`partner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `użytkownik_id` ON `project_travelo`.`skarga_na_partnera` (`klient_id` ASC) VISIBLE;

CREATE INDEX `partner_id` ON `project_travelo`.`skarga_na_partnera` (`partner_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`specjalne_żądanie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`specjalne_żądanie` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`specjalne_żądanie` (
  `żądanie_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `opis` TEXT NOT NULL,
  `typ` ENUM('rezerwacja_grupowa', 'żądanie_vip', 'wycieczka_niestandardowa') NOT NULL,
  `status` ENUM('oczekujące', 'skontaktowano', 'rozwiązane') NULL DEFAULT 'oczekujące',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`żądanie_id`),
  CONSTRAINT `specjalne_żądania_ibfk_1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `użytkownik_id` ON `project_travelo`.`specjalne_żądanie` (`klient_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`statystyka_systemu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`statystyka_systemu` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`statystyka_systemu` (
  `statystyka_id` INT NOT NULL AUTO_INCREMENT,
  `data_statystyki` DATE NOT NULL,
  `aktywni_użytkownicy` INT NOT NULL,
  `całkowite_rezerwacje` INT NULL DEFAULT NULL,
  `całkowity_przychód` DECIMAL(12,2) NOT NULL,
  `nowi_użytkownicy` INT NULL DEFAULT NULL,
  PRIMARY KEY (`statystyka_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `project_travelo`.`szablon_powiadomień`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`szablon_powiadomień` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`szablon_powiadomień` (
  `szablon_id` INT NOT NULL AUTO_INCREMENT,
  `typ` ENUM('email', 'sms') NOT NULL,
  `zdarzenie_wyzwalające` VARCHAR(100) NOT NULL,
  `temat` VARCHAR(255) NULL DEFAULT NULL,
  `treść` TEXT NOT NULL,
  PRIMARY KEY (`szablon_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `project_travelo`.`szablon_wsparcia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`szablon_wsparcia` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`szablon_wsparcia` (
  `szablon_id` INT NOT NULL AUTO_INCREMENT,
  `tytuł` VARCHAR(100) NOT NULL,
  `wiadomość` TEXT NOT NULL,
  `kategoria` ENUM('konto', 'rezerwacja', 'płatność', 'promocja', 'inne') NOT NULL,
  PRIMARY KEY (`szablon_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `project_travelo`.`ulubione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`ulubione` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`ulubione` (
  `ulubione_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `typ_uslugi` ENUM('atrakcja', 'zakwaterowanie') NOT NULL,
  `atrakcja_id` INT NULL DEFAULT NULL,
  `zakwaterowanie_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ulubione_id`),
  CONSTRAINT `fk_ulubione_atrakcja1`
    FOREIGN KEY (`atrakcja_id`)
    REFERENCES `project_travelo`.`atrakcja` (`atrakcja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ulubione_zakwaterowanie1`
    FOREIGN KEY (`zakwaterowanie_id`)
    REFERENCES `project_travelo`.`zakwaterowanie` (`zakwaterowanie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ulubione_ibfk_1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `idx_unique_favorite` ON `project_travelo`.`ulubione` (`klient_id` ASC, `typ_uslugi` ASC) VISIBLE;

CREATE INDEX `idx_typ_elementu_obiekt_id` ON `project_travelo`.`ulubione` (`typ_uslugi` ASC) VISIBLE;

CREATE INDEX `fk_ulubione_atrakcja1_idx` ON `project_travelo`.`ulubione` (`atrakcja_id` ASC) VISIBLE;

CREATE INDEX `fk_ulubione_zakwaterowanie1_idx` ON `project_travelo`.`ulubione` (`zakwaterowanie_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`użytkownik_partnera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`użytkownik_partnera` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`użytkownik_partnera` (
  `użytkownik_partner_id` INT NOT NULL AUTO_INCREMENT,
  `partner_id` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `hasło_hash` VARCHAR(255) NOT NULL,
  `imię` VARCHAR(100) NULL DEFAULT NULL,
  `rola` ENUM('właściciel', 'menedżer', 'personel') NULL DEFAULT 'menedżer',
  `jest_aktywny` TINYINT(1) NULL DEFAULT '1',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`użytkownik_partner_id`),
  CONSTRAINT `użytkownicy_partnerów_ibfk_1`
    FOREIGN KEY (`partner_id`)
    REFERENCES `project_travelo`.`partner` (`partner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `email` ON `project_travelo`.`użytkownik_partnera` (`email` ASC) VISIBLE;

CREATE INDEX `partner_id` ON `project_travelo`.`użytkownik_partnera` (`partner_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`wiadomość_zgłoszenia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`wiadomość_zgłoszenia` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`wiadomość_zgłoszenia` (
  `wiadomość_id` INT NOT NULL AUTO_INCREMENT,
  `zgłoszenie_id` INT NOT NULL,
  `typ_nadawcy` ENUM('użytkownik', 'agent', 'system') NOT NULL,
  `nadawca_id` INT NULL DEFAULT NULL,
  `wiadomość` TEXT NOT NULL,
  `wysłano_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`wiadomość_id`),
  CONSTRAINT `wiadomości_zgłoszeń_ibfk_1`
    FOREIGN KEY (`zgłoszenie_id`)
    REFERENCES `project_travelo`.`zgłoszenie_wsparcia` (`zgłoszenie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `zgłoszenie_id` ON `project_travelo`.`wiadomość_zgłoszenia` (`zgłoszenie_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`wycieczka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`wycieczka` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`wycieczka` (
  `wycieczka_id` INT NOT NULL AUTO_INCREMENT,
  `tytuł` VARCHAR(255) NOT NULL,
  `opis` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`wycieczka_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `project_travelo`.`zakwaterowanie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`zakwaterowanie` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`zakwaterowanie` (
  `zakwaterowanie_id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(255) NOT NULL,
  `opis` TEXT NOT NULL,
  `typ` VARCHAR(50) NOT NULL,
  `gwiazdy` INT NULL DEFAULT NULL,
  `miasto_id` INT NOT NULL,
  `cena_za_noc` DECIMAL(10,2) NOT NULL,
  `udogodnienia` TEXT NOT NULL,
  `polityka_anulowania` TEXT NULL DEFAULT NULL,
  `partner_id` INT NOT NULL,
  PRIMARY KEY (`zakwaterowanie_id`),
  CONSTRAINT `zakwaterowania_ibfk_1`
    FOREIGN KEY (`miasto_id`)
    REFERENCES `project_travelo`.`miasto` (`miasto_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `zakwaterowania_ibfk_2`
    FOREIGN KEY (`partner_id`)
    REFERENCES `project_travelo`.`partner` (`partner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `miasto_id` ON `project_travelo`.`zakwaterowanie` (`miasto_id` ASC) VISIBLE;

CREATE INDEX `partner_id` ON `project_travelo`.`zakwaterowanie` (`partner_id` ASC) VISIBLE;

CREATE INDEX `idx_cena_za_noc` ON `project_travelo`.`zakwaterowanie` (`cena_za_noc` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`zdjęcie_atrakcji`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`zdjęcie_atrakcji` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`zdjęcie_atrakcji` (
  `zdjęcie_id` INT NOT NULL AUTO_INCREMENT,
  `atrakcja_id` INT NOT NULL,
  `url_zdjęcia` TEXT NOT NULL,
  PRIMARY KEY (`zdjęcie_id`),
  CONSTRAINT `zdjęcia_atrakcji_ibfk_1`
    FOREIGN KEY (`atrakcja_id`)
    REFERENCES `project_travelo`.`atrakcja` (`atrakcja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `atrakcja_id` ON `project_travelo`.`zdjęcie_atrakcji` (`atrakcja_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`zgłoszenie_wsparcia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`zgłoszenie_wsparcia` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`zgłoszenie_wsparcia` (
  `zgłoszenie_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `temat` VARCHAR(255) NOT NULL,
  `opis` TEXT NOT NULL,
  `status` ENUM('otwarte', 'w_trakcie', 'rozwiązane', 'zamknięte') NOT NULL DEFAULT 'otwarte',
  `priorytet` ENUM('niski', 'średni', 'wysoki', 'krytyczny') NOT NULL DEFAULT 'średni',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `rozwiązano_w` TIMESTAMP NULL DEFAULT NULL,
  `administrator_id` INT NOT NULL,
  PRIMARY KEY (`zgłoszenie_id`),
  CONSTRAINT `fk_zgłoszenie_wsparcia_administrator1`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `project_travelo`.`administrator` (`administrator_id`),
  CONSTRAINT `zgłoszenia_wsparcia_ibfk_1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `użytkownik_id` ON `project_travelo`.`zgłoszenie_wsparcia` (`klient_id` ASC) VISIBLE;

CREATE INDEX `fk_zgłoszenie_wsparcia_administrator1_idx` ON `project_travelo`.`zgłoszenie_wsparcia` (`administrator_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`śledzenie_recenzji`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`śledzenie_recenzji` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`śledzenie_recenzji` (
  `śledzenie_id` INT NOT NULL AUTO_INCREMENT,
  `recenzja_id` INT NOT NULL,
  `notatka_rozwiązania` TEXT NULL DEFAULT NULL,
  `rozwiązane` TINYINT(1) NULL DEFAULT '0',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `administrator_id` INT NOT NULL,
  PRIMARY KEY (`śledzenie_id`),
  CONSTRAINT `fk_śledzenie_recenzji_administrator1`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `project_travelo`.`administrator` (`administrator_id`),
  CONSTRAINT `śledzenie_recenzji_ibfk_1`
    FOREIGN KEY (`recenzja_id`)
    REFERENCES `project_travelo`.`recenzja` (`recenzja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `recenzja_id` ON `project_travelo`.`śledzenie_recenzji` (`recenzja_id` ASC) VISIBLE;

CREATE INDEX `fk_śledzenie_recenzji_administrator1_idx` ON `project_travelo`.`śledzenie_recenzji` (`administrator_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `project_travelo`.`żądania_zwrotu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_travelo`.`żądania_zwrotu` ;

CREATE TABLE IF NOT EXISTS `project_travelo`.`żądania_zwrotu` (
  `żądanie_zwrotu_id` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `rezerwacja_id` INT NOT NULL,
  `powód` TEXT NULL DEFAULT NULL,
  `status` ENUM('oczekujące', 'zatwierdzone', 'odrzucone') NOT NULL DEFAULT 'oczekujące',
  `utworzono_w` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`żądanie_zwrotu_id`),
  CONSTRAINT `żądania_zwrotu_ibfk_1`
    FOREIGN KEY (`klient_id`)
    REFERENCES `project_travelo`.`klient` (`klient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `żądania_zwrotu_ibfk_2`
    FOREIGN KEY (`rezerwacja_id`)
    REFERENCES `project_travelo`.`rezerwacja` (`rezerwacja_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `użytkownik_id` ON `project_travelo`.`żądania_zwrotu` (`klient_id` ASC) VISIBLE;

CREATE INDEX `rezerwacja_id` ON `project_travelo`.`żądania_zwrotu` (`rezerwacja_id` ASC) VISIBLE;

USE `project_travelo`;

DELIMITER $$

USE `project_travelo`$$
DROP TRIGGER IF EXISTS `project_travelo`.`check_oczekujący_klient_before_insert` $$
USE `project_travelo`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `project_travelo`.`check_oczekujący_klient_before_insert`
BEFORE INSERT ON `project_travelo`.`oczekujący_klient`
FOR EACH ROW
BEGIN
    IF (NEW.atrakcja_id IS NULL AND NEW.zakwaterowanie_id IS NULL) OR
       (NEW.atrakcja_id IS NOT NULL AND NEW.zakwaterowanie_id IS NOT NULL) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Dokładnie jedno z pól atrakcja_id lub zakwaterowanie_id musi być ustawione';
    END IF;
    IF NEW.typ_uslugi = 'atrakcja' AND NEW.atrakcja_id IS NULL THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Jeśli typ_uslugi to atrakcja, atrakcja_id musi być ustawione';
    END IF;
    IF NEW.typ_uslugi = 'zakwaterowanie' AND NEW.zakwaterowanie_id IS NULL THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Jeśli typ_uslugi to zakwaterowanie, zakwaterowanie_id musi być ustawione';
    END IF;
END$$


USE `project_travelo`$$
DROP TRIGGER IF EXISTS `project_travelo`.`check_recenzja_before_insert` $$
USE `project_travelo`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `project_travelo`.`check_recenzja_before_insert`
BEFORE INSERT ON `project_travelo`.`recenzja`
FOR EACH ROW
BEGIN
    IF NEW.ocena < 1 OR NEW.ocena > 5 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ocena musi być między 1 a 5';
    END IF;
END$$


USE `project_travelo`$$
DROP TRIGGER IF EXISTS `project_travelo`.`check_recenzja_obiekt_id_before_insert` $$
USE `project_travelo`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `project_travelo`.`check_recenzja_obiekt_id_before_insert`
BEFORE INSERT ON `project_travelo`.`recenzja`
FOR EACH ROW
BEGIN
    IF NEW.typ_elementu = 'atrakcja' THEN
        IF NOT EXISTS (
            SELECT 1 FROM `project_travelo`.`atrakcja`
            WHERE `atrakcja_id` = NEW.obiekt_id
        ) THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Nieprawidłowy atrakcja_id dla typ_elementu = atrakcja';
        END IF;
    ELSEIF NEW.typ_elementu = 'zakwaterowanie' THEN
        IF NOT EXISTS (
            SELECT 1 FROM `project_travelo`.`zakwaterowanie`
            WHERE `zakwaterowanie_id` = NEW.obiekt_id
        ) THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Nieprawidłowy zakwaterowanie_id dla typ_elementu = zakwaterowanie';
        END IF;
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
